const express=require('express')
const createPost=require('../controller/post/CreatePost')
const getPostsByUserId = require('../controller/post/getPostsByUserId')
const deletePost = require('../controller/post/DeletePost')
const likePost = require('../controller/post/LikePost')
const getLikeByPostId = require('../controller/post/getLikeByPostId')
const protectRouter = require('./ProtectRouter')
const getPostsPagination = require('../controller/post/GetPostsPagination')
const getPostsPaginationInGroup = require('../controller/post/GetPostsPaginationGroup')
const postRouter=express.Router()

// postRouter.post('/create',protectRouter,createPost)
postRouter.get('/all/user',protectRouter,getPostsByUserId)
postRouter.delete('/delete',protectRouter,deletePost)
postRouter.put('/like-post',protectRouter,likePost)
postRouter.get('/getLike',protectRouter,getLikeByPostId)
postRouter.get('/posts',protectRouter,getPostsPagination)
postRouter.get('/posts/group',protectRouter,getPostsPaginationInGroup)
module.exports=postRouter